---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_3_2_1: true
    ubtu22cis_rule_3_2_2: true
    ubtu22cis_is_router: false
    ubtu22cis_ipv6_disable: 'sysctl'  # or 'grub'
    ubtu22cis_sysctl_network_conf: '/etc/sysctl.conf'

  tasks:
    - name: "3.2.1 | PATCH | Ensure packet redirect sending is disabled"
      block:
        - name: "3.2.1 | PATCH | Ensure packet redirect sending is disabled | Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^{{ item }} ="
            line: "{{ item }} = 0"
            create: yes
          loop:
            - net.ipv4.conf.all.send_redirects
            - net.ipv4.conf.default.send_redirects

        - name: "3.2.1 | PATCH | Ensure packet redirect sending is disabled | Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_2_1
        - not ubtu22cis_is_router
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.2.1
        - packet_redirect
        - sysctl

    - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled"
      block:
        - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled | IPv4 settings"
          block:
            - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled | Set sysctl parameter"
              ansible.builtin.lineinfile:
                path: "{{ ubtu22cis_sysctl_network_conf }}"
                regexp: "^net.ipv4.ip_forward ="
                line: "net.ipv4.ip_forward = 0"
                create: yes

            - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled | Apply sysctl settings"
              ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
              changed_when: false

        - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled | IPv6 settings"
          block:
            - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled | Set sysctl parameter"
              ansible.builtin.lineinfile:
                path: "{{ ubtu22cis_sysctl_network_conf }}"
                regexp: "^net.ipv6.conf.all.forwarding ="
                line: "net.ipv6.conf.all.forwarding = 0"
                create: yes

            - name: "3.2.2 | PATCH | Ensure IP forwarding is disabled | Apply sysctl settings"
              ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
              changed_when: false
          when: ubtu22cis_ipv6_disable == 'sysctl'

      when:
        - ubtu22cis_rule_3_2_2
        - not ubtu22cis_is_router
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.2.2
        - ip_forwarding
        - sysctl
