---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_3_5_2_1: true
    ubtu22cis_rule_3_5_2_2: true
    ubtu22cis_rule_3_5_2_3: true
    ubtu22cis_rule_3_5_2_4: true
    ubtu22cis_rule_3_5_2_5: true
    ubtu22cis_rule_3_5_2_6: true
    ubtu22cis_rule_3_5_2_7: true
    ubtu22cis_rule_3_5_2_8: true
    ubtu22cis_rule_3_5_2_9: true
    ubtu22cis_rule_3_5_2_10: true
    ubtu22cis_firewall_package: "nftables"

  tasks:
    - name: "3.5.2.1 | AUDIT | Ensure nftables is installed"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.1'
      when:
        - ubtu22cis_rule_3_5_2_1
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - automated
        - audit
        - rule_3.5.2.1
        - nftables

    - name: "3.5.2.2 | AUDIT | Ensure ufw is uninstalled or disabled with nftables"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.2'
      when:
        - ubtu22cis_rule_3_5_2_2
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - automated
        - audit
        - rule_3.5.2.2
        - nftables

    - name: "3.5.2.3 | AUDIT | Ensure iptables are flushed with nftables"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.3'
      when:
        - ubtu22cis_rule_3_5_2_3
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - manual
        - audit
        - rule_3.5.2.3
        - nftables

    - name: "3.5.2.4 | AUDIT | Ensure a nftables table exists"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.4'
      when:
        - ubtu22cis_rule_3_5_2_4
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.5.2.4
        - nftables

    - name: "3.5.2.5 | AUDIT | Ensure nftables base chains exist"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.5'
      when:
        - ubtu22cis_rule_3_5_2_5
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - automated
        - audit
        - rule_3.5.2.5
        - nftables

    - name: "3.5.2.6 | AUDIT | Ensure nftables loopback traffic is configured"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.6'
      when:
        - ubtu22cis_rule_3_5_2_6
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - automated
        - audit
        - rule_3.5.2.6
        - nftables

    - name: "3.5.2.7 | AUDIT | Ensure nftables outbound and established connections are configured"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.7'
      when:
        - ubtu22cis_rule_3_5_2_7
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - manual
        - audit
        - rule_3.5.2.7
        - nftables

    - name: "3.5.2.8 | AUDIT | Ensure nftables default deny firewall policy"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.8'
      when:
        - ubtu22cis_rule_3_5_2_8
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - automated
        - audit
        - rule_3.5.2.8
        - nftables

    - name: "3.5.2.9 | AUDIT | Ensure nftables service is enabled"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.9'
      when:
        - ubtu22cis_rule_3_5_2_9
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - automated
        - audit
        - rule_3.5.2.9
        - nftables

    - name: "3.5.2.10 | AUDIT | Ensure nftables rules are permanent"
      block:
        - name: "Message out warning"
          ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

        - name: "Set warning count"
          ansible.builtin.import_tasks:
            file: warning_facts.yml
      vars:
        warn_control_id: '3.5.2.10'
      when:
        - ubtu22cis_rule_3_5_2_10
        - ubtu22cis_firewall_package == "nftables"
      tags:
        - level1-server
        - level1-workstation
        - automated
        - audit
        - rule_3.5.2.10
        - nftables
