---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_3_3_1: true
    ubtu22cis_rule_3_3_2: true
    ubtu22cis_rule_3_3_3: true
    ubtu22cis_rule_3_3_4: true
    ubtu22cis_rule_3_3_5: true
    ubtu22cis_rule_3_3_6: true
    ubtu22cis_rule_3_3_7: true
    ubtu22cis_rule_3_3_8: true
    ubtu22cis_rule_3_3_9: true
    ubtu22cis_is_router: false
    ubtu22cis_ipv6_disable: 'sysctl'  # or 'grub'
    ubtu22cis_ipv6_required: true
    ubtu22cis_sysctl_network_conf: '/etc/sysctl.conf'

  tasks:
    - name: "3.3.1 | PATCH | Ensure source routed packets are not accepted | IPv4 settings"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^{{ item }} ="
            line: "{{ item }} = 0"
            create: yes
          loop:
            - net.ipv4.conf.all.accept_source_route
            - net.ipv4.conf.default.accept_source_route

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_1
        - not ubtu22cis_is_router
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.1
        - routed_packets
        - sysctl

    - name: "3.3.1 | PATCH | Ensure source routed packets are not accepted | IPv6 settings"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^{{ item }} ="
            line: "{{ item }} = 0"
            create: yes
          loop:
            - net.ipv6.conf.all.accept_source_route
            - net.ipv6.conf.default.accept_source_route

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_1
        - ubtu22cis_ipv6_required
        - ubtu22cis_ipv6_disable == 'sysctl'
        - not ubtu22cis_is_router
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.1
        - routed_packets
        - sysctl

    - name: "3.3.2 | PATCH | Ensure ICMP redirects are not accepted | IPv4 settings"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^{{ item }} ="
            line: "{{ item }} = 0"
            create: yes
          loop:
            - net.ipv4.conf.all.accept_redirects
            - net.ipv4.conf.default.accept_redirects

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_2
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.2
        - icmp
        - sysctl

    - name: "3.3.2 | PATCH | Ensure ICMP redirects are not accepted | IPv6 settings"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^{{ item }} ="
            line: "{{ item }} = 0"
            create: yes
          loop:
            - net.ipv6.conf.all.accept_redirects
            - net.ipv6.conf.default.accept_redirects

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_2
        - ubtu22cis_ipv6_required
        - ubtu22cis_ipv6_disable == 'sysctl'
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.2
        - icmp
        - sysctl

    - name: "3.3.3 | PATCH | Ensure secure ICMP redirects are not accepted"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^{{ item }} ="
            line: "{{ item }} = 0"
            create: yes
          loop:
            - net.ipv4.conf.all.secure_redirects
            - net.ipv4.conf.default.secure_redirects

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_3
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.3
        - icmp
        - sysctl

    - name: "3.3.4 | PATCH | Ensure suspicious packets are logged"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^{{ item }} ="
            line: "{{ item }} = 1"
            create: yes
          loop:
            - net.ipv4.conf.all.log_martians
            - net.ipv4.conf.default.log_martians

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_4
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.4
        - suspicious_packets
        - sysctl

    - name: "3.3.5 | PATCH | Ensure broadcast ICMP requests are ignored"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^net.ipv4.icmp_echo_ignore_broadcasts ="
            line: "net.ipv4.icmp_echo_ignore_broadcasts = 1"
            create: yes

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_5
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.5
        - icmp
        - sysctl

    - name: "3.3.6 | PATCH | Ensure bogus ICMP responses are ignored"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^net.ipv4.icmp_ignore_bogus_error_responses ="
            line: "net.ipv4.icmp_ignore_bogus_error_responses = 1"
            create: yes

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_6
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.6
        - icmp
        - sysctl

    - name: "3.3.7 | PATCH | Ensure Reverse Path Filtering is enabled"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^{{ item }} ="
            line: "{{ item }} = 1"
            create: yes
          loop:
            - net.ipv4.conf.all.rp_filter
            - net.ipv4.conf.default.rp_filter

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_7
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.7
        - reverse_path_filtering
        - sysctl

    - name: "3.3.8 | PATCH | Ensure TCP SYN Cookies is enabled"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^net.ipv4.tcp_syncookies ="
            line: "net.ipv4.tcp_syncookies = 1"
            create: yes

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_8
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.8
        - tcp_syn_cookies
        - sysctl

    - name: "3.3.9 | PATCH | Ensure IPv6 router advertisements are not accepted"
      block:
        - name: "Set sysctl parameters"
          ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_sysctl_network_conf }}"
            regexp: "^{{ item }} ="
            line: "{{ item }} = 0"
            create: yes
          loop:
            - net.ipv6.conf.all.accept_ra
            - net.ipv6.conf.default.accept_ra

        - name: "Apply sysctl settings"
          ansible.builtin.shell: sysctl -p "{{ ubtu22cis_sysctl_network_conf }}"
          changed_when: false

      when:
        - ubtu22cis_rule_3_3_9
        - ubtu22cis_ipv6_required
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_3.3.9
        - ipv6
        - router_advertisements
        - sysctl
