---
- name: "3.2.1 | PATCH | Ensure packet redirect sending is disabled"
  block:
    - name: "3.2.1 | PATCH | Disable packet redirect sending"
      ansible.builtin.command:
        cmd: sysctl -w {{ item }}=0
      with_items:
        - net.ipv4.conf.all.send_redirects
        - net.ipv4.conf.default.send_redirects
      notify: Flush ipv4 route table
  when:
    - ubtu22cis_rule_3_2_1
    - not ubtu22cis_is_router
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_3.2.1
    - packet_redirect
    - sysctl

- name: "3.2.2 | PATCH | Ensure IP forwarding is disabled"
  block:
    - name: "3.2.2 | PATCH | Disable IP forwarding for IPv4"
      ansible.builtin.command:
        cmd: sysctl -w net.ipv4.ip_forward=0
      notify:
        - Flush ipv4 route table

    - name: "3.2.2 | PATCH | Disable IP forwarding for IPv6"
      ansible.builtin.command:
        cmd: sysctl -w net.ipv6.conf.all.forwarding=0
      when: ubtu22cis_ipv6_disable == 'sysctl'
      notify:
        - Flush ipv6 route table

  when:
    - ubtu22cis_rule_3_2_2
    - not ubtu22cis_is_router
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_3.2.2
    - ip_forwarding
    - sysctl
