---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_3_4_1: true
    ubtu22cis_rule_3_4_2: true
    ubtu22cis_rule_3_4_3: true
    ubtu22cis_rule_3_4_4: true

  tasks:
    - name: "3.4.1 | PATCH | Ensure DCCP is disabled | modprobe"
      block:
        - name: "Ensure dccp is disabled via modprobe"
          ansible.builtin.lineinfile:
            path: /etc/modprobe.d/dccp.conf
            regexp: '^(#)?install dccp(\s|$)'
            line: "install dccp /bin/true"
            create: true

        - name: "Blacklist dccp"
          ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist dccp(\s|$)"
            line: "blacklist dccp"
            create: true
            mode: '0600'

      when:
        - ubtu22cis_rule_3_4_1
      tags:
        - level2-server
        - level2-workstation
        - automated
        - patch
        - rule_3.4.1
        - dccp

    - name: "3.4.2 | PATCH | Ensure SCTP is disabled | modprobe"
      block:
        - name: "Ensure sctp is disabled via modprobe"
          ansible.builtin.lineinfile:
            path: /etc/modprobe.d/sctp.conf
            regexp: '^(#)?install sctp(\s|$)'
            line: "install sctp /bin/true"
            create: true

        - name: "Blacklist sctp"
          ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist sctp(\s|$)"
            line: "blacklist sctp"
            create: true
            mode: '0600'

      when:
        - ubtu22cis_rule_3_4_2
      tags:
        - level2-server
        - level2-workstation
        - automated
        - patch
        - rule_3.4.2
        - sctp

    - name: "3.4.3 | PATCH | Ensure RDS is disabled | modprobe"
      block:
        - name: "Ensure rds is disabled via modprobe"
          ansible.builtin.lineinfile:
            path: /etc/modprobe.d/rds.conf
            regexp: '^(#)?install rds(\s|$)'
            line: "install rds /bin/true"
            create: true

        - name: "Blacklist rds"
          ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist rds(\s|$)"
            line: "blacklist rds"
            create: true
            mode: '0600'

      when:
        - ubtu22cis_rule_3_4_3
      tags:
        - level2-server
        - level2-workstation
        - automated
        - patch
        - rule_3.4.3
        - rds

    - name: "3.4.4 | PATCH | Ensure TIPC is disabled | modprobe"
      block:
        - name: "Ensure tipc is disabled via modprobe"
          ansible.builtin.lineinfile:
            path: /etc/modprobe.d/tipc.conf
            regexp: '^(#)?install tipc(\s|$)'
            line: "install tipc /bin/true"
            create: true

        - name: "Blacklist tipc"
          ansible.builtin.lineinfile:
            path: /etc.modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist tipc(\s|$)"
            line: "blacklist tipc"
            create: true
            mode: '0600'

      when:
        - ubtu22cis_rule_3_4_4
      tags:
        - level2-server
        - level2-workstation
        - automated
        - patch
        - rule_3.4.4
        - tipc
