---
- name: CIS Ubuntu Hardening - File Permissions
  hosts: all
  become: yes

  tasks:
    - name: "6.1.1 | PATCH | Ensure permissions on /etc/passwd are configured"
      ansible.builtin.file:
        path: /etc/passwd
        owner: root
        group: root
        mode: '0644'
      when: ubtu22cis_rule_6_1_1
      tags:
        - level1-server
        - level1-workstation
        - patch
        - permissions
        - rule_6.1.1

    - name: "6.1.2 | PATCH | Ensure permissions on /etc/passwd- are configured"
      ansible.builtin.file:
        path: /etc/passwd-
        owner: root
        group: root
        mode: '0644'
      when: ubtu22cis_rule_6_1_2
      tags:
        - level1-server
        - level1-workstation
        - patch
        - permissions
        - rule_6.1.2

    - name: "6.1.3 | PATCH | Ensure permissions on /etc/group are configured"
      ansible.builtin.file:
        path: /etc/group
        owner: root
        group: root
        mode: '0644'
      when: ubtu22cis_rule_6_1_3
      tags:
        - level1-server
        - level1-workstation
        - patch
        - permissions
        - rule_6.1.3

    - name: "6.1.4 | PATCH | Ensure permissions on /etc/group- are configured"
      ansible.builtin.file:
        path: /etc/group-
        owner: root
        group: root
        mode: '0644'
      when: ubtu22cis_rule_6_1_4
      tags:
        - level1-server
        - level1-workstation
        - patch
        - permissions
        - rule_6.1.4

    - name: "6.1.5 | PATCH | Ensure permissions on /etc/shadow are configured"
      ansible.builtin.file:
        path: /etc/shadow
        owner: root
        group: root
        mode: '0640'
      when: ubtu22cis_rule_6_1_5
      tags:
        - level1-server
        - level1-workstation
        - patch
        - permissions
        - rule_6.1.5

    - name: "6.1.6 | PATCH | Ensure permissions on /etc/shadow- are configured"
      ansible.builtin.file:
        path: /etc/shadow-
        owner: root
        group: root
        mode: '0640'
      when: ubtu22cis_rule_6_1_6
      tags:
        - level1-server
        - level1-workstation
        - patch
        - permissions
        - rule_6.1.6

    - name: "6.1.7 | PATCH | Ensure permissions on /etc/gshadow are configured"
      ansible.builtin.file:
        path: /etc/gshadow
        owner: root
        group: root
        mode: '0640'
      when: ubtu22cis_rule_6_1_7
      tags:
        - level1-server
        - level1-workstation
        - patch
        - permissions
        - rule_6.1.7

    - name: "6.1.8 | PATCH | Ensure permissions on /etc/gshadow- are configured"
      ansible.builtin.file:
        path: /etc/gshadow-
        owner: root
        group: root
        mode: '0640'
      when: ubtu22cis_rule_6_1_8
      tags:
        - level1-server
        - level1-workstation
        - patch
        - permissions
        - rule_6.1.8

    - name: "6.1.9 | PATCH | Ensure no world writable files exist"
      block:
        - name: "Get list of world-writable files"
          ansible.builtin.shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002
          failed_when: false
          changed_when: false
          register: rhel_09_6_1_9_perms_results

        - name: "Adjust world-writable files if they exist (Configurable)"
          ansible.builtin.file:
            path: '{{ item }}'
            mode: o-w
            state: touch
          loop: "{{ rhel_09_6_1_9_perms_results.stdout_lines
