---
# SELinux Setup Tasks
- name: Ensure the system supports SELinux
  command: selinuxenabled
  ignore_errors: yes
  register: selinux_check

- name: Enable SELinux if it is disabled
  command: "sed -i 's/^SELINUX=disabled/SELINUX=permissive/' /etc/selinux/config"
  when: selinux_check.rc != 0

- name: Reboot the system to apply SELinux configuration changes
  reboot:
    reboot_timeout: 300
  when: selinux_check.rc != 0

- name: Ensure SELinux packages are installed
  apt:
    name:
      - selinux-basics
      - selinux-policy-default
      - auditd
      - audispd-plugins
    state: present
    update_cache: yes

- name: Set SELinux mode to enforcing in configuration
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: 'SELINUX=enforcing'

- name: Ensure SELinux is set to enforcing
  command: setenforce 1
  when: ansible_distribution == "Ubuntu"

- name: Check SELinux status
  command: getenforce
  register: selinux_status

# - name: Fail if SELinux is not enforcing
#   fail:
#     msg: "SELinux is not set to enforcing"
#   when: selinux_status.stdout != "Enforcing"

# Existing CIS Tasks
- name: "6.1.1 | PATCH | Ensure permissions on /etc/passwd are configured"
  ansible.builtin.file:
      path: /etc/passwd
      owner: root
      group: root
      mode: '0644'
  when:
      - ubtu22cis_rule_6_1_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - permissions
      - rule_6.1.1

# (Rest of the CIS tasks follow)
