---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_1_1_3_1: true
    ubtu22cis_rule_1_1_3_2: true
    ubtu22cis_rule_1_1_3_3: true
    mount_names: []

  tasks:
    - name: "1.1.3.1 | AUDIT | Ensure /var is a separate partition"
      block:
        - name: "1.1.3.1 | AUDIT | Ensure /var is a separate partition | Check if /var is already a separate partition"
          command: mountpoint /var
          register: var_mountpoint_check
          ignore_errors: true

        - name: "1.1.3.1 | AUDIT | Ensure /var is a separate partition | Create /var partition"
          block:
            - name: "Create /var partition"
              command: parted -s /dev/sda mkpart primary ext4 2GB 3GB
              register: parted_output
              ignore_errors: true

            - name: "Create filesystem on /var partition"
              command: mkfs.ext4 /dev/sda3
              when: parted_output.changed

            - name: "Add /var partition to /etc/fstab"
              lineinfile:
                path: /etc/fstab
                line: '/dev/sda3  /var  ext4  defaults,nosuid,nodev  0  2'
              when: parted_output.changed

            - name: "Mount /var partition"
              command: mount -a
          when: var_mountpoint_check.rc != 0
          ignore_errors: true

        - name: "1.1.3.1 | WARN | Ensure /var is a separate partition | warn_count"
          set_fact:
            warn_control_id: '1.1.3.1'
            warn_message: "The partition {{ required_mount }} is not found."
      vars:
        required_mount: '/var'
      when:
        - required_mount not in mount_names
        - ubtu22cis_rule_1_1_3_1
      tags:
        - level2-server
        - level2-workstation
        - automated
        - audit
        - rule_1.1.3.1
        - var

    - name: "1.1.3.2 | PATCH | Ensure nodev option set on /var partition"
      set_fact:
        var_partition_mount_options: "{{ var_partition_mount_options | default([]) + ['nodev'] }}"
      changed_when: true
      notify: Writing and remounting var
      vars:
        required_mount: '/var'
      when:
        - required_mount in mount_names
        - ubtu22cis_rule_1_1_3_2
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.1.3.2
        - var

    - name: "1.1.3.3 | PATCH | Ensure nosuid option set on /var partition"
      set_fact:
        var_partition_mount_options: "{{ var_partition_mount_options | default([]) + ['nosuid'] }}"
      changed_when: true
      notify: Writing and remounting var
      vars:
        required_mount: '/var'
      when:
        - required_mount in mount_names
        - ubtu22cis_rule_1_1_3_3
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.1.3.3
        - var

  handlers:
    - name: Writing and remounting var
      command: mount -o remount /var
