- name: "1.1.5.1 | AUDIT | Ensure /var/log is a separate partition"
  block:
    - name: "1.1.5.1 | AUDIT | Ensure /var/log is a separate partition | Absent"
      ansible.builtin.debug:
        msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

    - name: "1.1.5.1 | WARN | Ensure /var/log is a separate partition | warn_count"
      ansible.builtin.import_tasks:
        file: warning_facts.yml
  vars:
    warn_control_id: '1.1.5.1'
    required_mount: '/var/log'
  when:
    - required_mount not in mount_names
    - ubtu22cis_rule_1_1_5_1
  tags:
    - level2-server
    - level2-workstation
    - automated
    - audit
    - rule_1.1.5.1
    - varlog

- name: |
    "1.1.5.2 | PATCH | Ensure /var/log partition includes the nodev option"
    "1.1.5.3 | PATCH | Ensure /var/log partition includes the noexec option"
    "1.1.5.4 | PATCH | Ensure /var/log partition includes the nosuid option"
  block:
    - name: "1.1.5.2 | PATCH | Update /etc/fstab with nodev, noexec, nosuid options for /var/log"
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^(\S+\s+/var/log\s+\S+\s+\S+\s+)'
        line: '\1defaults,noexec,nodev,nosuid 0 0'
        backrefs: yes
      when:
        - item.mount == "/var/log"
        - ubtu22cis_rule_1_1_5_2 or
          ubtu22cis_rule_1_1_5_3 or
          ubtu22cis_rule_1_1_5_4

    - name: "1.1.5.2 | PATCH | Remount /var/log with updated options"
      ansible.builtin.command:
        cmd: mount -o remount /var/log
      notify: Remount var_log
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_1.1.5.2
    - rule_1.1.5.3
    - rule_1.1.5.4
    - varlog
