---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_1_5_1: true
    ubtu22cis_rule_1_5_2: true
    ubtu22cis_rule_1_5_3: true
    ubtu22cis_rule_1_5_4: true
    ubtu22cis_sysctl_kernel_conf: /etc/sysctl.d/99-sysctl.conf
    ubtu22cis_purge_apt: true

  tasks:
    - name: "1.5.1 | PATCH | Ensure address space layout randomization (ASLR) is enabled | Set active kernel parameter"
      ansible.posix.sysctl:
        name: kernel.randomize_va_space
        value: '2'
        state: present
        sysctl_file: "{{ ubtu22cis_sysctl_kernel_conf }}"
        reload: true
        sysctl_set: true
        ignoreerrors: true
      when:
        - ubtu22cis_rule_1_5_1
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.5.1
        - aslr

    - name: "1.5.2 | PATCH | Ensure prelink is not installed"
      block:
        - name: "1.5.2 | PATCH | Ensure prelink is not installed | Restore binaries to normal"
          ansible.builtin.shell: prelink -ua
          changed_when: false
          failed_when: false
          ignore_errors: true

        - name: "1.5.2 | PATCH | Ensure prelink is not installed | Remove prelink package"
          ansible.builtin.package:
            name: prelink
            state: absent
            purge: "{{ ubtu22cis_purge_apt }}"
      when:
        - ubtu22cis_rule_1_5_2
        - "'prelink' in ansible_facts.packages"
      tags:
       
