---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_1_1_7_1: true
    ubtu22cis_rule_1_1_7_2: true
    ubtu22cis_rule_1_1_7_3: true
    mount_names: []

  tasks:
    - name: "1.1.7.1 | AUDIT | Ensure /home is a separate partition"
      block:
        - name: "1.1.7.1 | AUDIT | Ensure /home is a separate partition | Check if /home is already a separate partition"
          command: mountpoint /home
          register: home_mountpoint_check
          ignore_errors: true

        - name: "1.1.7.1 | AUDIT | Ensure /home is a separate partition | Create /home partition"
          block:
            - name: "Create /home partition"
              command: parted -s /dev/sda mkpart primary ext4 6GB 7GB
              register: parted_output
              ignore_errors: true

            - name: "Create filesystem on /home partition"
              command: mkfs.ext4 /dev/sda7
              when: parted_output.changed

            - name: "Add /home partition to /etc/fstab"
              lineinfile:
                path: /etc/fstab
                line: '/dev/sda7  /home  ext4  defaults,nosuid,nodev  0  2'
              when: parted_output.changed

            - name: "Mount /home partition"
              command: mount -a
          when: home_mountpoint_check.rc != 0
          ignore_errors: true

        - name: "1.1.7.1 | WARN | Ensure /home is a separate partition | warn_count"
          set_fact:
            warn_control_id: '1.1.7.1'
            warn_message: "The partition {{ required_mount }} is not found."
      vars:
        required_mount: '/home'
      when:
        - required_mount not in mount_names
        - ubtu22cis_rule_1_1_7_1
      tags:
        - level2-server
        - level2-workstation
        - automated
        - audit
        - rule_1.1.7.1
        - home

    - name: "1.1.7.2 | PATCH | Ensure nodev option set on /home partition"
      set_fact:
        home_partition_mount_options: "{{ home_partition_mount_options | default([]) + ['nodev'] }}"
      changed_when: true
      notify: Writing and remounting home
      vars:
        required_mount: '/home'
      when:
        - required_mount in mount_names
        - ubtu22cis_rule_1_1_7_2
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.1.7.2
        - home

    - name: "1.1.7.3 | PATCH | Ensure nosuid option set on /home partition"
      set_fact:
        home_partition_mount_options: "{{ home_partition_mount_options | default([]) + ['nosuid'] }}"
      changed_when: true
      notify: Writing and remounting home
      vars:
        required_mount: '/home'
      when:
        - required_mount in mount_names
        - ubtu22cis_rule_1_1_7_3
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.1.7.3
        - home

  handlers:
    - name: Writing and remounting home
      command: mount -o remount /home
