---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_1_2_1: true
    ubtu22cis_rule_1_2_2: true

  tasks:
    - name: "1.2.1 | AUDIT | Ensure package manager repositories are configured"
      block:
        - name: "1.2.1 | AUDIT | Ensure package manager repositories are configured | Get repositories"
          ansible.builtin.shell: apt-cache policy
          changed_when: false
          failed_when: false
          check_mode: false
          register: ubtu22cis_1_2_1_apt_policy

        - name: "1.2.1 | AUDIT | Ensure package manager repositories are configured | Message out repository configs"
          ansible.builtin.debug:
            msg:
              - "Warning!! Below are the apt package repositories"
              - "Please review to make sure they conform to your site's policies"
              - "{{ ubtu22cis_1_2_1_apt_policy.stdout_lines }}"

        - name: "1.2.1 | WARN | Ensure package manager repositories are configured | warn_count"
          set_fact:
            warn_control_id: '1.2.1'
            warn_message: "The current package manager repositories configuration may not meet your site policies. Please review the repositories listed above."

      when:
        - ubtu22cis_rule_1_2_1
      tags:
        - level1-server
        - level1-workstation
        - manual
        - audit
        - rule_1.2.1
        - apt

    - name: "1.2.2 | AUDIT | Ensure GPG keys are configured"
      block:
        - name: "1.2.2 | AUDIT | Ensure GPG keys are configured | Get apt gpg keys"
          ansible.builtin.shell: apt-key list
          changed_when: false
          failed_when: false
          check_mode: false
          register: ubtu22cis_1_2_2_apt_gpgkeys

        - name: "1.2.2 | AUDIT | Ensure GPG keys are configured | Message out apt gpg keys"
          ansible.builtin.debug:
            msg:
              - "Warning!! Below are the apt gpg keys configured"
              - "Please review to make sure they are configured in accordance with site policy"
              - "{{ ubtu22cis_1_2_2_apt_gpgkeys.stdout_lines }}"

        - name: "1.2.2 | WARN | Ensure GPG keys are configured | warn_count"
          set_fact:
            warn_control_id: '1.2.2'
            warn_message: "The current GPG keys configuration may not meet your site policies. Please review the keys listed above."

      when:
        - ubtu22cis_rule_1_2_2
      tags:
        - level1-server
        - level1-workstation
        - manual
        - audit
        - rule_1.2.2
        - gpg
        - keys
