---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_1_1_1_1: true
    ubtu22cis_rule_1_1_1_2: true
    ubtu22cis_rule_1_1_1_3: true
    snap_pkg_mgr: { "stdout": "0" }
    squashfs_builtin: { "stdout": "0" }

  tasks:
    - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/cramfs.conf
        regexp: '^(#)?install cramfs(\\s|$)'
        line: install cramfs /bin/true
        create: true
      when: ubtu22cis_rule_1_1_1_1

    - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist cramfs(\\s|$)"
        line: "blacklist cramfs"
        create: true
        mode: '0600'
      when: ubtu22cis_rule_1_1_1_1

    - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Disable cramfs"
      shell: lsmod | grep cramfs && rmmod cramfs || true
      when: 
        - ansible_connection != 'docker'
        - ubtu22cis_rule_1_1_1_1
      notify: Update_Initramfs

    - name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/squashfs.conf
        regexp: '^(#)?install squashfs(\\s|$)'
        line: install squashfs /bin/true
        create: true
      when: 
        - ubtu22cis_rule_1_1_1_2
        - snap_pkg_mgr.stdout == "0"
        - squashfs_builtin.stdout == "0"

    - name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist squashfs(\\s|$)"
        line: "blacklist squashfs"
        create: true
        mode: '0600'
      when: 
        - ubtu22cis_rule_1_1_1_2
        - snap_pkg_mgr.stdout == "0"
        - squashfs_builtin.stdout == "0"

    - name: "1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled | Disable squashfs"
      shell: lsmod | grep squashfs && rmmod squashfs || true
      when: 
        - ansible_connection != 'docker'
        - ubtu22cis_rule_1_1_1_2
        - snap_pkg_mgr.stdout == "0"
        - squashfs_builtin.stdout == "0"
      notify: Update_Initramfs

    - name: "1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/udf.conf
        regexp: '^(#)?install udf(\\s|$)'
        line: install udf /bin/true
        create: true
      when: ubtu22cis_rule_1_1_1_3

    - name: "1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled | blacklist"
      lineinfile:
        path: /etc/modprobe.d/blacklist.conf
        regexp: "^(#)?blacklist udf(\\s|$)"
        line: "blacklist udf"
        create: true
        mode: '0600'
      when: ubtu22cis_rule_1_1_1_3

    - name: "1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled | Disable udf"
      shell: lsmod | grep udf && rmmod udf || true
      when: 
        - ansible_connection != 'docker'
        - ubtu22cis_rule_1_1_1_3
      notify: Update_Initramfs

  handlers:
    - name: Update_Initramfs
      command: update-initramfs -u
