---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_1_1_10: true
    ubtu22cis_allow_usb_storage: false

  tasks:
    - name: "1.1.10 | PATCH | Disable USB Storage | Set modprobe config"
      block:
        - name: "Set modprobe config to disable USB storage"
          ansible.builtin.lineinfile:
            path: /etc/modprobe.d/usb_storage.conf
            regexp: '^install usb-storage'
            line: 'install usb-storage /bin/true'
            create: true

        - name: "Update initramfs after setting modprobe config"
          command: update-initramfs -u
          when: ansible_os_family == "Debian"

      when: ubtu22cis_rule_1_1_10 and not ubtu22cis_allow_usb_storage

    - name: "1.1.10 | PATCH | Disable USB Storage | Blacklist usb-storage"
      block:
        - name: "Blacklist usb-storage module"
          ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            line: 'blacklist usb-storage'
            insertafter: EOF

        - name: "Update initramfs after blacklisting usb-storage"
          command: update-initramfs -u
          when: ansible_os_family == "Debian"

      when: ubtu22cis_rule_1_1_10 and not ubtu22cis_allow_usb_storage

    - name: "1.1.10 | PATCH | Disable USB Storage | Remove usb-storage module"
      block:
        - name: "Remove usb-storage module"
          shell: |
            if lsmod | grep -q usb_storage; then
              modprobe -r usb-storage
            fi
          when: ansible_connection != 'docker'

        - name: "Update initramfs after removing usb-storage module"
          command: update-initramfs -u
          when: ansible_os_family == "Debian"

      when: ubtu22cis_rule_1_1_10 and not ubtu22cis_allow_usb_storage

  tags:
    - level1-server
    - level2-workstation
    - automated
    - patch
    - rule_1.1.10
    - usb_storage
