---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_1_7_1: true
    ubtu22cis_rule_1_7_2: true
    ubtu22cis_rule_1_7_3: true
    ubtu22cis_rule_1_7_4: true
    ubtu22cis_rule_1_7_5: true
    ubtu22cis_rule_1_7_6: true
    ubtu22cis_disable_dynamic_motd: true

  tasks:
    - name: "1.7.1 | PATCH | Ensure message of the day is configured properly"
      block:
        - name: "Ensure message of the day is configured properly | motd"
          ansible.builtin.template:
            src: ../../../templates/motd.j2
            dest: /etc/motd

        - name: "Ensure message of the day is configured properly | disable dynamic_motd"
          ansible.builtin.lineinfile:
            path: /etc/pam.d/sshd
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            backrefs: true
          loop:
            - { regexp: '(session\s+optional\s+pam_motd.so\s+motd=/run/motd.dynamic)', line: '# \1' }
            - { regexp: '(session\s+optional\s+pam_motd.so noupdate)', line: '# \1' }
            - { regexp: '# Pam_motd.so disabled for CIS benchmark', line: '# Pam_motd.so disabled for CIS benchmark' }
          when: ubtu22cis_disable_dynamic_motd
      when:
        - ubtu22cis_rule_1_7_1
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.7.1
        - motd

    - name: "1.7.2 | PATCH | Ensure local login warning banner is configured properly"
      block:
        - name: "Ensure local login warning banner is configured properly | issue"
          ansible.builtin.template:
            src: ../../../templates/issue.j2
            dest: /etc/issue

        - name: "Ensure local login warning banner is kept on package upgrade | issue"
          ansible.builtin.command:
            cmd: dpkg-divert --add /etc/issue
      when:
        - ubtu22cis_rule_1_7_2
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.7.2
        - banner

    - name: "1.7.3 | PATCH | Ensure remote login warning banner is configured properly"
      block:
        - name: "Ensure remote login warning banner is configured properly | issue.net"
          ansible.builtin.template:
            src: ../../../templates/issue.net.j2
            dest: /etc/issue.net

        - name: "Ensure remote login warning banner is kept on package upgrade | issue.net"
          ansible.builtin.command:
            cmd: dpkg-divert --add /etc/issue.net
      when:
        - ubtu22cis_rule_1_7_3
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.7.3
        - banner

    - name: "1.7.4 | PATCH | Ensure permissions on /etc/motd are configured"
      ansible.builtin.file:
        path: /etc/motd
        owner: root
        group: root
        mode: '0644'
      when:
        - ubtu22cis_rule_1_7_4
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.7.4
        - permissions
        - motd

    - name: "1.7.5 | PATCH | Ensure permissions on /etc/issue are configured"
      ansible.builtin.file:
        path: /etc/issue
        owner: root
        group: root
        mode: '0644'
      when:
        - ubtu22cis_rule_1_7_5
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.7.5
        - permissions
        - banner

    - name: "1.7.6 | PATCH | Ensure permissions on /etc/issue.net are configured"
      ansible.builtin.file:
        path: /etc/issue.net
        owner: root
        group: root
        mode: '0644'
      when:
        - ubtu22cis_rule_1_7_6
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.7.6
        - permissions
        - banner
