---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_set_boot_pass: true
    ubtu22cis_rule_1_4_1: true
    ubtu22cis_ask_passwd_to_boot: false
    ubtu22cis_grub_user_file: "/etc/grub.d/00_user"
    ubtu22cis_grub_file: "/boot/grub/grub.cfg"
    ubtu22cis_rule_1_4_2: true
    ubtu22cis_rule_1_4_3: true
    ubtu22cis_set_grub_user_pass: true
    ubtu22cis_grub_user: "grubuser"
    ubtu22cis_grub_user_passwd: "hashed_password"

  tasks:
    - name: "1.4.1 | PATCH | Ensure bootloader password is set"
      block:
        - name: "1.4.1 | PATCH | Ensure bootloader password is set"
          ansible.builtin.template:
            src: etc/grub.d/00_user.j2
            dest: "{{ ubtu22cis_grub_user_file }}"
            owner: root
            group: root
            mode: '0755'

        - name: "1.4.1 | PATCH | Ensure bootloader password is set | Allow unrestricted boot"
          ansible.builtin.lineinfile:
            path: "/etc/grub.d/10_linux"
            regexp: '(^CLASS="--class gnu-linux --class gnu --class os).*"$'
            line: '\g<1> --unrestricted"'
            backrefs: true
          when: not ubtu22cis_ask_passwd_to_boot

        - name: "1.4.1 | PATCH | Update GRUB"
          ansible.builtin.command: update-grub

      when:
        - ubtu22cis_set_boot_pass
        - ubtu22cis_rule_1_4_1
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.4.1
        - grub

    - name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured"
      block:
        - name: "1.4.2 | AUDIT | Ensure permissions on bootloader config are configured | Check for GRUB file"
          ansible.builtin.stat:
            path: "{{ ubtu22cis_grub_file }}"
          check_mode: false
          register: ubtu22cis_1_4_2_grub_cfg_status

        - name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured | Set permissions"
          ansible.builtin.file:
            path: "{{ ubtu22cis_grub_file }}"
            owner: root
            group: root
            mode: '0400'
          when:
            - ubtu22cis_1_4_2_grub_cfg_status.stat.exists

      when:
        - ubtu22cis_rule_1_4_2
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.4.2
        - grub

    - name: "1.4.3 | PATCH | Ensure authentication required for single user mode"
      ansible.builtin.user:
        name: "{{ ubtu22cis_grub_user }}"
        password: "{{ ubtu22cis_grub_user_passwd }}"
      when:
        - ubtu22cis_rule_1_4_3
        - ubtu22cis_set_grub_user_pass
      tags:
        - level1-server
        - level1-workstation
        - automated
        - patch
        - rule_1.4.3
        - passwd
        - grub
