- name: "1.1.3.1 | AUDIT | Ensure /var is a separate partition"
  block:
    - name: "1.1.3.1 | AUDIT | Ensure /var is a separate partition | Absent"
      ansible.builtin.debug:
        msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

    - name: "1.1.3.1 | WARN | Ensure /var is a separate partition | warn_count"
      ansible.builtin.import_tasks:
        file: warning_facts.yml
  vars:
    warn_control_id: '1.1.3.1'
    required_mount: '/var'
  when:
    - required_mount not in mount_names
    - ubtu22cis_rule_1_1_3_1
  tags:
    - level2-server
    - level2-workstation
    - automated
    - audit
    - rule_1.1.3.1
    - var

- name: "1.1.3.2 | PATCH | Ensure /var partition includes the nodev and nosuid options"
  block:
    - name: "1.1.3.2 | PATCH | Update /etc/fstab with nodev and nosuid options for /var"
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^(\S+\s+/var\s+\S+\s+\S+)'
        line: '\1, nodev,nosuid 0 2'
        backrefs: yes

    - name: "1.1.3.2 | PATCH | Remount /var with updated options"
      ansible.builtin.command:
        cmd: mount -o remount /var
      notify: Remount var
  when:
    - ubtu22cis_rule_1_1_3_2 or
      ubtu22cis_rule_1_1_3_3
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_1.1.3.2
    - rule_1.1.3.3
    - var
