---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_1_1_8_1: true
    ubtu22cis_rule_1_1_8_2: true
    ubtu22cis_rule_1_1_8_3: true

  tasks:
    - name: "1.1.8.1 | Ensure nodev option set on /dev/shm"
      shell: |
        if ! mount | grep -q '/dev/shm.*nodev'; then
          mount -o remount,nodev,nosuid,noexec /dev/shm
        fi
      when: ubtu22cis_rule_1_1_8_1

    - name: "1.1.8.2 | Ensure nosuid option set on /dev/shm"
      shell: |
        if ! mount | grep -q '/dev/shm.*nosuid'; then
          mount -o remount,nodev,nosuid,noexec /dev/shm
        fi
      when: ubtu22cis_rule_1_1_8_2

    - name: "1.1.8.3 | Ensure noexec option set on /dev/shm"
      shell: |
        if ! mount | grep -q '/dev/shm.*noexec'; then
          mount -o remount,nodev,nosuid,noexec /dev/shm
        fi
      when: ubtu22cis_rule_1_1_8_3

    - name: "Ensure /dev/shm entry in /etc/fstab"
      lineinfile:
        path: /etc/fstab
        regexp: '^tmpfs\s+/dev/shm\s+tmpfs'
        line: "tmpfs /dev/shm tmpfs defaults,nodev,nosuid,noexec 0 0"
        create: true
