---
- name: "1.1.10 | PATCH | Disable USB Storage"
  block:
      - name: "1.1.10 | PATCH | Disable USB Storage | Set modprobe config"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/usb_storage.conf
            regexp: '^install usb-storage'
            line: 'install usb-storage /bin/true'
            create: true
        notify: Update_Initramfs

      - name: "1.1.10 | PATCH | Disable USB Storage | Blacklist usb-storage"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            line: 'blacklist usb-storage'
            insertafter: EOF
        notify: Update_Initramfs

      - name: "1.1.10 | PATCH | Disable USB Storage | Remove usb-storage module"
        ansible.builtin.command:
            cmd: modprobe -r usb-storage
        when: ansible_connection != 'docker'
        notify: Update_Initramfs
  when:
      - ubtu22cis_rule_1_1_10
      - not ubtu22cis_allow_usb_storage
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.10
      - usb_storage
