---
- name: |
    "1.1.8.1 | PATCH | Ensure nodev option set on /dev/shm partition"
    "1.1.8.2 | PATCH | Ensure nosuid option set on /dev/shm partition"
    "1.1.8.3 | PATCH | Ensure noexec option set on /dev/shm partition"
  block:
    - name: "1.1.8.1 | PATCH | Update /etc/fstab with nodev, nosuid, noexec options for /dev/shm"
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^(\S+\s+/dev/shm\s+\S+\s+)(\S*)'
        line: '\1defaults,{% if ubtu22cis_rule_1_1_8_1 %}nodev,{% endif %}{% if ubtu22cis_rule_1_1_8_2 %}nosuid,{% endif %}{% if ubtu22cis_rule_1_1_8_3 %}noexec{% endif %}'
      when:
        - ubtu22cis_rule_1_1_8_1 or
          ubtu22cis_rule_1_1_8_2 or
          ubtu22cis_rule_1_1_8_3

    - name: "1.1.8.1 | PATCH | Remount /dev/shm with updated options"
      ansible.builtin.command:
        cmd: mount -o remount /dev/shm
      notify: Remount dev_shm
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_1.1.8.1
    - rule_1.1.8.2
    - rule_1.1.8.3
    - dev_shm

