---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_4_2_1_1_1: true
    ubtu22cis_rule_4_2_1_1_2: true
    ubtu22cis_rule_4_2_1_1_3: true
    ubtu22cis_rule_4_2_1_1_4: true
    ubtu22cis_system_is_log_server: false
    ubtu22cis_remote_log_server: "http://remote-log-server"
    ubtu22cis_journal_upload_serverkeyfile: "/path/to/serverkeyfile"
    ubtu22cis_journal_servercertificatefile: "/path/to/servercertificatefile"
    ubtu22cis_journal_trustedcertificatefile: "/path/to/trustedcertificatefile"

  tasks:
    - name: "4.2.1.1.1 | PATCH | Ensure systemd-journal-remote is installed"
      apt:
        name: systemd-journal-remote
        state: present
      when:
        - ubtu22cis_rule_4_2_1_1_1
        - not ubtu22cis_system_is_log_server
      tags:
        - level1-server
        - level1-workstation
        - manual
        - patch
        - journald
        - rule_4.2.1.1.1

    - name: "4.2.1.1.2 | PATCH | Ensure systemd-journal-remote is configured"
      lineinfile:
        path: /etc/systemd/journal-upload.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      notify: Restart journald
      with_items:
        - { regexp: 'URL=', line: 'URL={{ ubtu22cis_remote_log_server }}' }
        - { regexp: 'ServerKeyFile=', line: 'ServerKeyFile={{ ubtu22cis_journal_upload_serverkeyfile }}' }
        - { regexp: 'ServerCertificateFile=', line: 'ServerCertificateFile={{ ubtu22cis_journal_servercertificatefile }}' }
        - { regexp: 'TrustedCertificateFile=', line: 'TrustedCertificateFile={{ ubtu22cis_journal_trustedcertificatefile }}' }
      when:
        - ubtu22cis_rule_4_2_1_1_2
        - not ubtu22cis_system_is_log_server
      tags:
        - level1-server
        - level1-workstation
        - manual
        - patch
        - journald
        - rule_4.2.1.1.2

    - name: "4.2.1.1.3 | PATCH | Ensure systemd-journal-remote is enabled"
      systemd:
        name: systemd-journal-upload
        state: started
        enabled: true
      when:
        - not ubtu22cis_system_is_log_server
        - ubtu22cis_rule_4_2_1_1_3
      tags:
        - level1-server
        - level1-workstation
        - manual
        - patch
        - journald
        - rule_4.2.1.1.3

    - name: "4.2.1.1.4 | PATCH | Ensure journald is not configured to receive logs from a remote client"
      systemd:
        name: systemd-journal-remote.socket
        state: stopped
        enabled: false
        masked: true
      when:
        - not ubtu22cis_system_is_log_server
        - ubtu22cis_rule_4_2_1_1_4
      tags:
        - level1-server
        - level1-workstation
        - patch
        - journald
        - rule_4.2.1.1.4

  handlers:
    - name: Restart journald
      systemd:
        name: systemd-journald
        state: restarted
