---
- hosts: localhost
  become: true
  vars:
    ubtu22cis_rule_4_1_4_1: true
    ubtu22cis_rule_4_1_4_2: true
    ubtu22cis_rule_4_1_4_3: true
    ubtu22cis_rule_4_1_4_4: true
    ubtu22cis_rule_4_1_4_5: true
    ubtu22cis_rule_4_1_4_6: true
    ubtu22cis_rule_4_1_4_7: true
    ubtu22cis_rule_4_1_4_8: true
    ubtu22cis_rule_4_1_4_9: true
    ubtu22cis_rule_4_1_4_10: true
    ubtu22cis_rule_4_1_4_11: true
    ubtu22cis_config_aide: true
    auditd_conf_files:
      files:
        - path: /etc/audit/auditd.conf
          mode: 0640

  tasks:
    - name: "4.1.4.1 | 4.1.4.2 | 4.1.4.3 | Ensure audit log files are mode 0640 or less permissive and owned by root"
      block:
        - name: "Discover audit log file"
          shell: grep ^log_file /etc/audit/auditd.conf | awk '{ print $NF }'
          register: audit_discovered_logfile
          changed_when: false

        - name: "Ensure audit log file is found"
          fail:
            msg: "Audit log file not found"
          when: audit_discovered_logfile.stdout == ""

        - name: "Get audit log file stats"
          stat:
            path: "{{ audit_discovered_logfile.stdout }}"
          register: auditd_logfile
          changed_when: false

        - name: "Ensure audit log file permissions and ownership"
          file:
            path: "{{ audit_discovered_logfile.stdout }}"
            mode: "0640"
            owner: root
            group: root
      when: ubtu22cis_rule_4_1_4_1 or ubtu22cis_rule_4_1_4_2 or ubtu22cis_rule_4_1_4_3
      tags:
        - level1-server
        - level1-workstation
        - patch
        - auditd
        - rule_4.1.4.1
        - rule_4.1.4.2
        - rule_4.1.4.3

    - name: "4.1.4.4 | Ensure the audit log directory is 0750 or more restrictive"
      block:
        - name: "Get audit log directory stats"
          stat:
            path: "{{ audit_discovered_logfile.stdout | dirname }}"
          register: auditlog_dir

        - name: "Ensure audit log directory permissions"
          file:
            path: "{{ audit_discovered_logfile.stdout | dirname }}"
            state: directory
            mode: '0750'
          when: not auditlog_dir.stat.mode is match('07(0|5)0')
      when: ubtu22cis_rule_4_1_4_4
      tags:
        - level1-server
        - level1-workstation
        - patch
        - auditd
        - rule_4.1.4.4

    - name: "4.1.4.5 | Ensure audit configuration files are 640 or more restrictive"
      file:
        path: "{{ item.path }}"
        mode: '0640'
      loop: "{{ auditd_conf_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      when: ubtu22cis_rule_4_1_4_5
      tags:
        - level1-server
        - level1-workstation
        - patch
        - auditd
        - rule_4.1.4.5

    - name: "4.1.4.6 | Ensure audit configuration files are owned by root"
      file:
        path: "{{ item.path }}"
        owner: root
      loop: "{{ auditd_conf_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      when: ubtu22cis_rule_4_1_4_6
      tags:
        - level1-server
        - level1-workstation
        - patch
        - auditd
        - rule_4.1.4.6

    - name: "4.1.4.7 | Ensure audit configuration files belong to group root"
      file:
        path: "{{ item.path }}"
        group: root
      loop: "{{ auditd_conf_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      when: ubtu22cis_rule_4_1_4_7
      tags:
        - level1-server
        - level1-workstation
        - patch
        - auditd
        - rule_4.1.4.7

    - name: "4.1.4.8 | Ensure audit tools are 755 or more restrictive"
      block:
        - name: "Get audit binary file stats"
          stat:
            path: "{{ item }}"
          register: audit_bins
          loop:
            - /sbin/auditctl
            - /sbin/aureport
            - /sbin/ausearch
            - /sbin/autrace
            - /sbin/auditd
            - /sbin/augenrules

        - name: "Ensure audit tool permissions"
          file:
            path: "{{ item.item }}"
            mode: '0750'
          loop: "{{ audit_bins.results }}"
          loop_control:
            label: "{{ item.item }}"
          when: not item.stat.mode is match('07(0|5)0')
      when: ubtu22cis_rule_4_1_4_8
      tags:
        - level1-server
        - level1-workstation
        - patch
        - auditd
        - rule_4.1.4.8

    - name: "4.1.4.9 | Ensure audit tools are owned by root"
      file:
        path: "{{ item }}"
        owner: root
        group: root
      loop:
        - /sbin/auditctl
        - /sbin/aureport
        - /sbin/ausearch
        - /sbin/autrace
        - /sbin/auditd
        - /sbin/augenrules
      when: ubtu22cis_rule_4_1_4_9
      tags:
        - level1-server
        - level1-workstation
        - patch
        - auditd
        - rule_4.1.4.9

    - name: "4.1.4.10 | Ensure audit tools belong to group root"
      file:
        path: "{{ item }}"
        group: root
      loop:
        - /sbin/auditctl
        - /sbin/aureport
        - /sbin/ausearch
        - /sbin/autrace
        - /sbin/auditd
        - /sbin/augenrules
      when: ubtu22cis_rule_4_1_4_10
      tags:
        - level1-server
        - level1-workstation
        - patch
        - auditd
        - rule_4.1.4.10

    - name: "4.1.4.11 | Ensure cryptographic mechanisms are used to protect the integrity of audit tools"
      lineinfile:
        path: /etc/aide/aide.conf
        regexp: "{{ item }}"
        line: "{{ item }}"
      loop:
        - '# Audit tools'
        - /sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512
        - /sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512
        - /sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512
        - /sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512
        - /sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512
        - /sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512
      when: ubtu22cis_rule_4_1_4_11 and ubtu22cis_config_aide
      tags:
        - level1-server
        - level1-workstation
        - patch
        - auditd
        - rule_4.1.4.11
